
name: publish dotnet_azure_vm_main

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/dotnetverification@v1
      - name: Build DotNET35
        run: dotnet build --configuration Release
