
name: publish dotnet_azure_vm_main

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET35
        run:  cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\"
      - name: Run MS build
        run: .\MSBuild.exe /home/runner/work/ADUVerify/ADUVerify.sln
